services:
  calibreweb:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibreweb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ./config:/config
      - /mnt/sec/media/books:/books
    ports:
      - 3015:8083
    restart: unless-stopped
