services:
  grocy:
    image: lscr.io/linuxserver/grocy:latest
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
    volumes:
      - /mnt/sec/apps/grocy/config:/config
    ports:
      - 3022:80
    restart: unless-stopped
