services:
  guacamole:
    image: abesnier/guacamole
    container_name: guacamole
    volumes:
      - /mnt/sec/apps/guacamole/config:/config
    ports:
      - 3024:8080
    networks:             # optional:
      - windows_default   # to use the same network as windows-vm

networks:
  windows_default:
    external: true
