services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.6.0  # Specifies the Mealie Docker image and version.
    container_name: mealie                      # Names the container for easier management.
    restart: always                              # Ensures the container restarts automatically unless stopped.
    ports:
      - "3025:9000"                             # Maps port 9925 on the host to port 9000 in the container.
    deploy:
      resources:
        limits:
          memory: 1000M                         # Limits the container to use a maximum of 1000M of memory.
    volumes:
      - mealie-data:/app/data/                  # Persists data in a named volume.
    environment:
      - ALLOW_SIGNUP=true                       # Allows new user signups on the Mealie instance.
      - PUID=1000                               # Sets the user ID for the container.
      - PGID=1000                               # Sets the group ID for the container.
      - TZ=America/Anchorage                    # Sets the timezone for the container.
      - MAX_WORKERS=1                           # Limits the number of workers to 1.
      - WEB_CONCURRENCY=1                       # Sets the concurrency level for web workers.
      - BASE_URL=https://mealie.threeminuteslab.com  # The base URL where Mealie is accessed.

volumes:
  mealie-data:                                  # Declares a named volume for persisting application data.