services:
  postgres:
    container_name: zipline-db
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  zipline:
    container_name: zipline
    image: ghcr.io/diced/zipline
    restart: unless-stopped
    ports:
      - '3024:3000'
    environment:
      - CORE_SECRET=84jt74hfkgmhufjruglduwheufjtiep1
      - CORE_DATABASE_URL=postgres://postgres:postgres@postgres/postgres
    volumes:
      - './uploads:/zipline/uploads'
      - './public:/zipline/public'
    depends_on:
      - 'postgres'

volumes:
  pg_data: