# docker exec -it python-env bash
# cd /workspace/my_project
# python main.py
# 
# Ctrl + Shift + P → "Python: Select Interpreter"
# Enter interpreter path > Find
# /workspace/.pyenv/versions/3.x.x/bin/python
#
# pip install -r requirements.txt

services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    ports:
      - "3023:8080"
    volumes:
      - /mnt/sec/apps/codeserver/workspace:/home/coder/workspace
      - /mnt/sec/apps/codeserver/pyenv:/home/coder/.pyenv
    environment:
      - PASSWORD=yourpassword

  pyenv:
    image: ry4nyeo/codeserver-pyenv:latest
    container_name: pyenv
    ports:
      - "3024:3024"
    volumes:
      - /mnt/sec/apps/codeserver/workspace:/workspace
      - /mnt/sec/apps/codeserver/pyenv:/home/coder/.pyenv
    working_dir: /workspace
    tty: true
    stdin_open: true
    command: |
      /bin/bash -c "
      cd ~/.pyenv && git pull && 
      jupyter notebook --ip=0.0.0.0 --port=3024 --no-browser --allow-root & 
      exec bash"
