# docker exec -it python-env bash
# cd /workspace/my_project
# python main.py

# Ctrl + Shift + P → "Python: Select Interpreter"
# Enter interpreter path > Find
# /workspace/.pyenv/versions/3.x.x/bin/python

# pip install -r requirements.txt

services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    ports:
      - "3023:8080"  # Code-Server access
    volumes:
      - /mnt/sec/apps/codeserver/workspace:/home/coder/workspace  # Persist projects
      - /mnt/sec/apps/codeserver/pyenv:/home/coder/.pyenv  # Share Python env
    environment:
      - PASSWORD=yourpassword

  python-env:
    build: .
    container_name: python-env
    ports:
      - "3024:8888"  # Jupyter Notebook
    volumes:
      - /mnt/sec/apps/codeserver/workspace:/workspace  # Persist projects
      - /mnt/sec/apps/codeserver/pyenv:/home/coder/.pyenv  # Shared Python env
    working_dir: /workspace
    tty: true
    stdin_open: true
    command: |
      /bin/bash -c "
      cd ~/.pyenv && git pull && 
      jupyter notebook --ip=0.0.0.0 --port=3024 --no-browser --allow-root & 
      exec bash"
