# 1. post deploying compose, wait a good 3-5 minutes for database setup
# 2. then login with username (root) and password (initial_root_password)
#  docker exec gitlab cat /etc/gitlab/initial_root_password

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: 'gitlab.yourdomain.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.yourdomain.com:8080'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '8080:80'
      - '2224:22'
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    shm_size: '256m'
