# https://docs.gitlab.com/user/get_started/
# post deploying compose, wait 3-5 minutes for database setup (important)
# login with username (root) and password (initial_root_password)
#   docker exec gitlab cat /etc/gitlab/initial_root_password
# =====
# GitLab > Admin > CI/CD > Create Instance Runner
# Create a tag > Create Runner
#   docker exec -it gitlab-runner bash
#   gitlab-runner register  --url http://gitlab:80  --token glrt-<token>
# url:          http://gitlab:80
# description:  gitlab-runner
# executor:     docker
# image:        alpine
# =====
# config files: /etc/gitlab-runner/config.toml
# [runners.docker]
#   image = "docker:latest"
#   privileged = true
#   volumes = ["/var/run/docker.sock:/var/run/docker.sock"]
# =====
#   nano /etc/docker/daemon.json
#     "insecure-registries": ["gitlabregistry.domain.com"]
#   systemctl restart docker

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: 'gitlab.threeminuteslab.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.threeminuteslab.com'
        registry_external_url 'http://gitlabregistry.threeminuteslab.com'
        pages_external_url 'http://gitlabpages.threeminuteslab.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        gitlab_rails['pages_https'] = true
        gitlab_rails['gitlab_https'] = true
        gitlab_rails['registry_https'] = true
        gitlab_rails['registry_enabled'] = true
        gitlab_pages['enable'] = true
        gitlab_pages['inplace_chroot'] = true
        gitlab_pages['artifacts_server'] = true
        gitlab_pages['redirect_http'] = false
        nginx['listen_https'] = false
  
    ports:
      - '3028:80'
      - '2224:22'
      - '5001:5001'
      - '8090:8090'
    volumes:
      - /mnt/sec/apps/gitlab/config:/etc/gitlab
      - /mnt/sec/apps/gitlab/logs:/var/log/gitlab
      - /mnt/sec/apps/gitlab/data:/var/opt/gitlab
    shm_size: '256m'

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    depends_on:
      - gitlab
    volumes:
      - ./gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
