services:
  stirlingpdf:
    image: frooodle/s-pdf:latest
    container_name: stirlingpdf
    ports:
      - '3013:8080'
    restart: unless-stopped
    volumes:
      - /mnt/sec/apps/stirlingpdf/trainingData:/usr/share/tessdata #Required for extra OCR languages
      - /mnt/sec/apps/stirlingpdf/extraConfigs:/configs
#      - /mnt/sec/apps/stirlingpdf/customFiles:/customFiles/
#      - /mnt/sec/apps/stirlingpdf/logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB
