# https://tailscale.com/kb/1282/docker
# filebrowser runs at https://tailscale-ip:80
# filebrowser default user:password login = admin:admin
# samba maps at \\tailscale-up\mediadb
# samba default user:password login = toor:toor
# samba password change: smbpasswd toor

services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: tailscale
    environment:
      - TS_AUTHKEY=<get key from tailscale admin console>
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - /mnt/sec/apps/tailscale/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
      - /mnt/sec/media:/mnt/sec/media:z  # Mount the media directory for Samba access
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    volumes:
      - /mnt/sec:/srv
    network_mode: service:tailscale  # Filebrowser will share Tailscale's network
    restart: unless-stopped

  samba:
    image: dperson/samba
    container_name: samba
    environment:
      TZ: 'Asia/Singapore'
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /mnt/sec/media:/mnt/sec/media:z  # Mount the same directory for Samba
      - /mnt/sec/apps/tailscale/samba:/etc/samba  # Mount the custom smb.conf
    entrypoint: >
      bash -c "$(wget -qLO- https://github.com/therepos/proxmox/raw/main/tools/set-sambausers.sh)"
    network_mode: service:tailscale  # Use Tailscale's network stack
