# Must use https: and tls:no-verify
# User : kasm_user
# VNC_PW: password
# sudo chown -R 1000:1000 /mnt/sec/apps/brave/data
# sudo chown -R 1000:1000 /mnt/sec/apps/brave/downloads
# sudo chown -R 1000:1000 /mnt/sec/media/shared

services:
  brave:
    image: kasmweb/brave:1.18.0
    container_name: brave
    ports:
      - "3003:6901"
    environment:
      - VNC_PW=${VNC_PW}
      - LAUNCH_URL=${LAUNCH_URL}
      - KASM_RESTRICTED_FILE_CHOOSER=0
    shm_size: 1gb
    restart: unless-stopped
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
    volumes:
      - /mnt/sec/apps/brave/data:/home/kasm_user/.config/BraveSoftware/Brave-Browser
      - /mnt/sec/media/shared:/home/kasm-user/Downloads
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
