# Must use https: and tls:no-verify
# User : kasm_user
# Add environment variables VNC_PW to set password

services:
  brave:
    image: kasmweb/brave:1.18.0
    container_name: brave
    ports:
      - "3003:6901"
    environment:
      - VNC_PW=${VNC_PW}
      - LAUNCH_URL=${LAUNCH_URL}
    shm_size: 1gb
    restart: unless-stopped
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
    volumes:
      - /mnt/sec/apps/brave/data:/home/kasm-user/.config/BraveSoftware
      - /mnt/sec/apps/brave/downloads:/home/kasm-user/Downloads
      - /mnt/sec/media/shared:/home/kasm-user/shared
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

