# purpose: this runs codeserver container with pyenv container support
# navigate to python project directory:
#   docker exec -it python-env bash
#   cd /workspace/my_project
#   python main.py
# set python interpreter:
#   Ctrl + Shift + P → "Python: Select Interpreter"
#   Enter interpreter path > Find
#   /workspace/.pyenv/versions/3.x.x/bin/python
# install python requirements:
#   pip install -r requirements.txt
# dynamically set password or use env file:
#   JUPYTER_PASSWORD=mysecurepassword docker-compose up -d

services:
  codeserver:
    image: lscr.io/linuxserver/code-server:latest
    container_name: codeserver
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
      - PASSWORD=password #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /mnt/sec/apps/codeserver/workspace:/home/coder/workspace
    ports:
      - 3023:8443
    restart: unless-stopped

