# docker pull yanwk/comfyui-boot:cu128-slim
# deploy via portainer stack

services:
  comfyui:
    image: yanwk/comfyui-boot:cu128-slim
    container_name: comfyui
    ports:
      - "3030:8188"
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - CLI_ARGS=--disable-xformers
    shm_size: 2g
    runtime: nvidia
    restart: unless-stopped
    volumes:
      - /mnt/sec/apps/comfyui:/root
      - /mnt/sec/apps/comfyui/models:/root/ComfyUI/models
      - /mnt/sec/media/shared:/root/ComfyUI/output
      - /mnt/sec/media/shared:/root/ComfyUI/input