# 1. initial setup: disable runner and pages services.
# 2. get registration token by creating a runner in gitea.
# 3. re-enable runner and pages services.

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    ports:
      - "3029:3000"     # Web UI
      - "222:22"        # SSH
    volumes:
      - ./data:/data
    networks:
      - gitea

  runner:
    image: gitea/act_runner:latest
    container_name: gitea-runner
    restart: always
    depends_on:
      - gitea
    environment:
      - GITEA_INSTANCE_URL=https://gitea.domain.com
      - GITEA_RUNNER_REGISTRATION_TOKEN=sPfd1vvFMGcj9uN00HhRnuVMHOoicFcVf89CiguJ
      - GITEA_RUNNER_NAME=gitea-runner
      - GITEA_RUNNER_LABELS=ubuntu
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./runner:/data
      - /mnt/sec/apps/gitea/pages:/usr/share/nginx/html
    networks:
      - gitea

  pages:
    image: nginx:alpine
    container_name: gitea-pages
    volumes:
      - /mnt/sec/apps/gitea/pages:/usr/share/nginx/html
    ports:
      - "3030:80"
    networks:
      - gitea

  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    environment:
      - PASSWORD=password   # change this!
    user: "1000:1000"
    ports:
      - "3031:8080"
    volumes:
      - /mnt/sec/apps/gitea/pages/therepos:/home/coder/project:rw  # Mount Gitea repos
    networks:
      - gitea
            
networks:
  gitea:
    name: gitea-net
    driver: bridge