services:
  imagehub:
    image: ghcr.io/therepos/imagehub:latest
    container_name: imagehub
    restart: unless-stopped
    ports:
      - "3030:80"
    volumes:
      - /mnt/sec/apps/imagehub/stack.env:/etc/imagehub/stack.env
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
    labels:
      - "com.centurylinklabs.watchtower.enable=true"