services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: bridge  # Explicitly use bridge mode
    restart: unless-stopped
    runtime: nvidia
    environment:
      - TZ=Asia/Singapore
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
#   devices:
#     - /dev/dri:/dev/dri # iGPU
    volumes:
      - /mnt/sec/apps/jellyfin/config:/config
      - /mnt/sec/apps/jellyfin/cache:/cache
      - /mnt/sec/media:/media
    ports:
      - "3011:8096"
    cpus: "6"
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
    labels:
      - "com.centurylinklabs.watchtower.enable=true"