services:
  metube:
    image: alexta69/metube:latest
    container_name: metube
    network_mode: bridge
    restart: unless-stopped
    environment:
      - TZ=Asia/Singapore
    volumes:
      - /mnt/sec/apps/metube/downloads:/downloads
    ports:
      - "3010:8081"
    security_opt:
      - apparmor=unconfined
      - seccomp:unconfined