services:
  metube:
    image: alexta69/metube:latest
    container_name: metube
    ports:
      - "3010:8081"
    volumes:
      - /mnt/sec/media/music:/downloads
      - /mnt/sec/apps/metube:/config
    restart: unless-stopped
    security_opt:
      - apparmor=unconfined
      - seccomp:unconfined
      
  metubetag:
    image: ghcr.io/therepos/metubetag:latest
    container_name: metubetag
    volumes:
      - /mnt/sec/media/music:/music
      - /mnt/sec/apps/metube:/metube
    restart: unless-stopped