services:
  pdf-ai:
    image: ghcr.io/therepos/pdfai:latest
    container_name: pdf-ai
    ports:
      - "3024:8000"
    volumes:
      - ./data:/app/data
      - ./faiss_index:/app/faiss_index
    restart: unless-stopped
