# https://tailscale.com/kb/1282/docker
# update tailscale:
#   docker stop tailscale
#   docker rm tailscale
#   docker rmi tailscale/tailscale:latest
#   docker pull tailscale/tailscale:latest
#   Tailscale Admin Console > Regenerate Hash Key
#   docker compose up -d
#   docker exec tailscale tailscale version

services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: tailscale
    environment:
      - TS_AUTHKEY=<get key from tailscale admin console>
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - /mnt/sec/apps/tailscale/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
      - /mnt/sec/media:/mnt/sec/media:z  # Mount the media directory for Samba access
    cap_add:
      - net_admin
      - sys_module
    network_mode: host
    restart: unless-stopped

#   filebrowser:
#     image: filebrowser/filebrowser:latest
#     container_name: filebrowser
#     volumes:
#       - /mnt/sec:/srv
# #     - /:/srv  # Mount the entire root filesystem
#     network_mode: service:tailscale  # Filebrowser will share Tailscale's network
#     restart: unless-stopped

#   samba:
#     image: dperson/samba
#     container_name: samba
#     environment:
#       TZ: 'Asia/Singapore'
#     restart: unless-stopped
#     stdin_open: true
#     tty: true
#     volumes:
#       - /mnt/sec/media:/mnt/sec/media:z
#       - /mnt/sec/apps/tailscale/samba:/etc/samba
#     command: >
#       -s "mediadb;/mnt/sec/media;yes;no;no;admin;admin;admin"
#       -u "admin;admin"
#       -g "force user = admin"
#       -g "force group = admin"
#       -g "create mask = 0664"
#       -g "directory mask = 2775"
#       -g "force create mode = 0664"
#       -g "force directory mode = 2775"
#     network_mode: service:tailscale
