# https://tailscale.com/kb/1282/docker
# update tailscale:
#   docker stop tailscale
#   docker rm tailscale
#   docker rmi tailscale/tailscale:latest
#   docker pull tailscale/tailscale:latest
#   Tailscale Admin Console > Regenerate Auth Key: https://login.tailscale.com/admin/settings/keys
#   docker compose up -d
#   docker exec tailscale tailscale version

services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: tailscale
    environment:
      - TS_AUTHKEY=<get key from tailscale admin console>
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - /mnt/sec/apps/tailscale/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
      - /mnt/sec/media:/mnt/sec/media:z  # Mount the media directory for Samba access
    cap_add:
      - net_admin
      - sys_module
    network_mode: host
    restart: unless-stopped