services:
   vaultwarden:
      container_name: vaultwarden
      image: vaultwarden/server:latest
      volumes:
         - /mnt/sec/apps/vaultwarden/data/:/data/
      ports:
         - 3002:80
      restart: unless-stopped
      environment:
        - DOMAIN=https://domain.com
        - ADMIN_TOKEN=${ADMIN_TOKEN}                # 64-char
        - SMTP_HOST=smtp.zoho.com
        - SMTP_PORT=587
        - SMTP_FROM=${SMTP_FROM}                    # email address
        - SMTP_USERNAME=${SMTP_USERNAME}            # email address
        - SMTP_PASSWORD=${SMTP_PASSWORD}            # generate zoho-email app password
        - SMTP_SECURITY=starttls
      security_opt:
        - apparmor=unconfined
        - seccomp=unconfined
      labels:
         - "com.centurylinklabs.watchtower.enable=true"
