# issue: nvidia gpu passthrough only reach container level not windows

services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
      RAM_SIZE: "16G"
      CPU_CORES: "8"      
      DISK_SIZE: "128G"
      USERNAME: "windows"
      PASSWORD: "windows"
      REGION: "en-SG"
#     GPU: "Y"                  # uncomment for igpu passthrough
    devices:
      - /dev/kvm
      - /dev/net/tun
#     - /dev/dri                # uncomment for igpu passthrough
    cap_add:
      - NET_ADMIN
    volumes:
#     - /mnt/sec/media:/data    # uncomment for igpu passthrough
      - /mnt/sec/apps/.installers/Win11_24H2_English_x64.iso:/custom.iso
      - /mnt/sec/apps/windows/storage:/storage
    ports:
      - 3021:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    restart: always
    stop_grace_period: 2m
    networks:                 
      - windows_default         # to share the same network

networks:
  windows_default:
    external: true
