services:
  ffmpeg:
    image: linuxserver/ffmpeg
    container_name: ffmpeg
    runtime: nvidia  # Enables GPU acceleration
    volumes:
      - /mnt/sec/media/temp:/config  # Mounts the 'videos' directory from the host to /config inside the container
    working_dir: /config  # Sets the working directory
    stdin_open: true  # Keep container interactive
    tty: true
    command: [
      "-hwaccel", "nvdec",
      "-i", "/config/input.mkv",
      "-c:v", "h264_nvenc",
      "-b:v", "4M",
      "-vf", "scale=1280:720",
      "-c:a", "copy",
      "/config/output.mkv"
    ]
