name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Generate and commit templates.md if needed
        run: |
          BASE_SHA=${{ github.event.before }}
          if [ -z "$BASE_SHA" ] || ! git cat-file -e $BASE_SHA 2>/dev/null; then
            echo "No valid base SHA — running docgen unconditionally"
            python scripts/docgen-templates.py
          elif git diff --name-only $BASE_SHA ${{ github.sha }} | grep -E '^(apps/docker/|apps/installer|apps/tools/)'; then
            echo "Changes detected — running docgen"
            python scripts/docgen-templates.py
          else
            echo "No relevant changes → skipping docgen"
            exit 0
          fi

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/templates.md
          git diff --cached --quiet || git commit -m "Update templates.md"
          git push

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Sync and commit theme.css from template
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git clone --filter=blob:none --no-checkout https://x-access-token:${{ secrets.PAT }}@github.com/therepos/docusaurus.git temp-docusaurus
          cd temp-docusaurus
          git sparse-checkout init --cone
          git sparse-checkout set src/css/theme.css
          git checkout main
          cp src/css/theme.css ../src/css/theme.css
          cd ..
          rm -rf temp-docusaurus
          git add src/css/theme.css
          git commit -m "Sync theme.css from template" || echo "No changes"
          git push
                  
      - name: Build site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
