name: Generate Docker Compose Index

on:
  push:
    paths:
      - 'docker/**'
      - 'tools/index-compose.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Generate Docker Compose Index
        run: python tools/index-compose.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/listcompose.md
          git commit -m "Auto-update docker-compose index" || echo "No changes to commit"
          git push
