name: Sync theme

on:
  schedule:
    - cron: '0 0 * * *'  # every day at 00:00 UTC
  workflow_dispatch:

jobs:
  sync-theme:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Sync and commit theme from template
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git clone --filter=blob:none --no-checkout https://x-access-token:${{ secrets.PAT }}@github.com/therepos/docusaurus.git temp-docusaurus
          cd temp-docusaurus
          git sparse-checkout init --cone
          git sparse-checkout set src/css/theme.css footer.js
          git checkout main
          cp src/css/theme.css ../src/css/theme.css
          cp footer.js ../footer.js
          cd ..
          rm -rf temp-docusaurus
          git add src/css/theme.css footer.js
          git commit -m "Sync theme.css and footer.js from template" || echo "No changes"
          git push